<?php
/**
 * @file
 * Code for the BCR Banner feature.
 */

include_once 'bcr_banner.features.inc';
//include_once 'bcr_banner.install';


/**
 * Implements hook_init().
 *
 * Perform setup tasks for non-cached page requests.
 *
 * This hook is run at the beginning of the page request. It is typically
 * used to set up global parameters that are needed later in the request.
 * When this hook is called, all modules are already loaded in memory.
 *
 * This hook is not run on cached pages.
 *
 * To add CSS or JS that should be present on all pages, modules should not
 * implement this hook, but declare these files in their .info file.
 *
 * @see hook_boot()
 *
 *
 */
function bcr_banner_init() {
//  bcr_banner_flag_blogs_for_banner();
}

/**
 * Implements hook_node_view().
 *
 */
function bcr_banner_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full') {
//    bcr_banner_flag_blogs_for_banner();

  }
  $t=1;

}


function bcr_banner_flag_blogs_for_banner() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'blog')
    ->propertyCondition('status', 1);
  $entities = $query->execute();
  $flag = flag_get_flag('banner_include_flag');
  foreach ($entities['node'] as $val) {
    if ($flag && !$flag->is_flagged($val->nid)) {
      $t=1;
      $flag->flag('flag', $val->nid);
    }
  }
}