<?php
/**
 * @file bcr_player.module
 */



/**
 * Implements hook_init().
 */
function bcr_player_init() {
  /*
   * add js for the player
   */
//  drupal_add_js(drupal_get_path('module', 'bcr_player') . '/js/jquery.jplayer.min.js');
  drupal_add_library('bcr_player', 'jPlayer');
  drupal_add_js(drupal_get_path('module', 'bcr_player') . '/bcr_player.js');
}



/**
 * Implements hook_library().
 *
 *
 */
function bcr_player_library() {
  // Library One.
  $libraries['jPlayer'] = array(
    'title' => 'jPlayer',
    'website' => 'https://github.com/happyworm/jPlayer',
    'version' => '2.92',
    'js' => array(
      'sites/all/libraries/jPlayer/dist/jplayer/jquery.jplayer.min.js' => array()
    ),
  );
  return $libraries;
}