<?php

/**
 * @file bcr_blocks.module
 */

//drupal_add_js(drupal_get_path('module', 'bcr_blocks') .'/bcr_blocks.js');


/**
 * Implements hook_block_info().
 */
function bcr_blocks_block_info() {
  // BCR famous foto grid
  $blocks['bcr_channels_grid'] = array(
    'info' => t('BCR Channels grid view'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  // BCR persistent player
  $blocks['bcr_logo'] = array(
    'info' => t('BCR logo'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  // BCR persistent player
  $blocks['bcr_player'] = array(
    'info' => t('BCR player'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  // BCR Chat block
  $blocks['bcr_chat'] = array(
    'info' => t('BCR chat'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bcr_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'bcr_channels_grid':
      $block['content'] = bcr_channels_grid_block_render();
      break;
    case 'bcr_player':
      $block['content'] = bcr_player_block_render();
      break;
    case 'bcr_logo':
      $block['content'] = bcr_logo_block_render();
      break;
    case 'bcr_chat':
      $block['content'] = bcr_chat_block_render();
      break;
  }
  return $block;
}

/**
 * DEPRECATED
 *
 * Implements hook_menu().
 *
 * @return mixed
 */
function bcr_blocks_menu() {
//  $items['front'] = array(
//    'page callback' => 'bcr_front_page_getter',
//    'access arguments' => array('access content'),
//  );
//  return $items;
}

/**
 * Implements hook_views_pre_render
 *
 * @param $view
 */
function bcr_blocks_views_pre_render(&$view) {

}



/* **********************************
 * HELPER FUNCTIONS
 * **********************************/


/*
 * BLOCK RENDER CALLBACKS
 */

/**
 * BCR Channels block
 */
function bcr_channels_grid_block_render() {
  return views_embed_view('bcr_channels');
}

/**
 * BCR PLAYER block
 */
function bcr_player_block_render() {

  global $base_url;

//  $player = file_get_contents(drupal_get_path('module', 'bcr_player') . '/bcr-jplayer.inc');
//
//  return $player;
//  $streaming = module_invoke('menu', 'block_view', 'menu-streams');
  $block = '<div class="streaming-menu">';
  $block .= //render($streaming['content']);
  $block .= '</div>';
//  print $block['content'];

//  $player = '
//
//<div id="jquery_jplayer_1" class="jp-jplayer"></div>
//<div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
//	<div class="jp-type-single">
//		<div class="jp-gui jp-interface">
//			<div class="jp-controls">
//				<button class="jp-play" role="button" tabindex="0">play</button>
//				<button class="jp-stop" role="button" tabindex="0">stop</button>
//			</div>
//			<div class="jp-progress">
//				<div class="jp-seek-bar">
//					<div class="jp-play-bar"></div>
//				</div>
//			</div>
//			<div class="jp-volume-controls">
//				<button class="jp-mute" role="button" tabindex="0">mute</button>
//				<button class="jp-volume-max" role="button" tabindex="0">max volume</button>
//				<div class="jp-volume-bar">
//					<div class="jp-volume-bar-value"></div>
//				</div>
//			</div>
//		</div>
//		<div class="jp-no-solution">
//			<span>Update Required</span>
//			To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
//		</div>
//	</div>
//</div>
//
//  ';
  $player = '
    <div id="jquery_jplayer_1" class="jp-jplayer"></div>
   		<div class="jp-audio">

			  <div class="jp-type-single">
          <div id="jp_interface_1" class="jp-interface">
            <a href="/" class="bcr-logo" target="_parent"></a>
            <ul class="jp-controls">
              <li class="play-control"><a href="#" class="jp-play" tabindex="1">play</a></li>
              <li class="play-control"><a href="#" class="jp-pause" tabindex="1">pause</a></li>
              <li class="vol-control"><a href="#" class="jp-mute" tabindex="1">mute</a></li>
              <li class="vol-control"><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
            </ul>
          </div>
				<div id="jp_playlist_1" class="jp-playlist"></div>
			</div>
		</div>
  ';
//  <iframe  src="'. $base_url .'/sites/all/modules/custom/jplayer/bcr-jplayer.html"></iframe>

  return '
          <input type="checkbox" id="live-options-toggle" />

            <div class="live-options">
              <ul>
                <li><a href="http://tunein.com/radio/Berlin-Community-Radio-s209811/">TuneIn stream</a></li>
                <li><a href="'. $base_url .'/sites/all/themes/bcr_bootstrap/streams/bcr.m3u">M3U file</a></li>
                <li><a href="http://berlincommunityradio.out.airtime.pro:8000/berlincommunityradio_b">Stream</a></li>
                <!-- <li><a href="'. $base_url .'/sites/all/themes/bcr_bootstrap/streams/bcr.pls">PLS file</a></li> -->
                <li>
                  <label for="live-options-toggle">
                    X Close
                  </label>
                </li>
              </ul>
              
            </div>

          <div class="container">
            <label class="mobile-links" for="live-options-toggle">
              Listen Live
            </label>

            ' . $player . $block . '
          </div>
  ';
  // old player
//  return '<script src="http://player.radiocdn.com/iframe.js?hash=47cf418e3392826b9af8f67768e67551dbf3d9d6-450-135"></script>';
}

/**
 * BCR LOGO block
 */
function bcr_logo_block_render() {
  return '<div id="logo-element"><a class="logo"></a></div>';
}


/**
 * BCR CHAT block
 */
function bcr_chat_block_render() {
  // new style
//  return '<div id="tlkio" data-channel="bcr" data-theme="http://unremarkablegarden.com/bcr.css" style="width:50%;height:500px; margin: 0 auto;"></div><script async src="http://tlk.io/embed.js" type="text/javascript"></script>';
// old style
//  return '<div id="tlkio" data-channel="bcr" data-theme="http://unremarkablegarden.com/bcr.css" style="width:100%;height:600px;"></div><script async src="http://tlk.io/embed.js" type="text/javascript"></script>';
//  return '<div id="tlkio" data-channel="bcr" style="width:100%;height:400px;"></div><script async src="http://tlk.io/embed.js" type="text/javascript"></script>';
}


/*
 * PAGE RENDER CALLBACKS
 */

/**
 * HELPER FUNCTION / PAGE RENDER CALLBACK
 * Front page render
 */
function bcr_front_page_getter() {
  return bcr_channels_grid_block_render();
}



