<?php

/**
 * @file bcr_blocks.module
 */

/**
 * Implements hook_block_info().
 */
function bcr_blocks_block_info() {
  // BCR famous foto grid
  $blocks['bcr_channels_grid'] = array(
    'info' => t('BCR Channels grid view'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  // BCR persistent player
  $blocks['bcr_logo'] = array(
    'info' => t('BCR logo'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  // BCR persistent player
  $blocks['bcr_player'] = array(
    'info' => t('BCR player'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  // BCR Chat block
//  $blocks['bcr_chat'] = array(
//    'info' => t('BCR chat'),
//    'cache' => DRUPAL_NO_CACHE,
//  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bcr_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'bcr_channels_grid':
      $block['content'] = bcr_channels_grid_block_render();
      break;
    case 'bcr_player':
      $block['content'] = bcr_player_block_render();
      break;
    case 'bcr_logo':
      $block['content'] = bcr_logo_block_render();
      break;
//    case 'bcr_chat':
//      $block['content'] = bcr_chat_block_render();
//      break;
  }
  return $block;
}

///**
// * DEPRECATED
// *
// * Implements hook_menu().
// *
// * @return mixed
// */
//function bcr_blocks_menu() {
////  $items['front'] = array(
////    'page callback' => 'bcr_front_page_getter',
////    'access arguments' => array('access content'),
////  );
////  return $items;
//}

/**
 * Implements hook_views_pre_render
 *
 * @param $view
 */
function bcr_blocks_views_pre_render(&$view) {

}



/* **********************************
 * HELPER FUNCTIONS
 * **********************************/


/*
 * BLOCK RENDER CALLBACKS
 */

/**
 * BCR Channels block
 */
function bcr_channels_grid_block_render() {
  return views_embed_view('bcr_channels');
}

/**
 * BCR PLAYER block
 */
function bcr_player_block_render() {
  global $base_url;
  $block = '<div class="streaming-menu">';
  $block .= '</div>';
  $player = '
    <div id="jquery_jplayer_1" class="jp-jplayer"></div>
   		<div class="jp-audio">

			  <div class="jp-type-single">
          <div id="jp_interface_1" class="jp-interface">
            <a href="/" class="bcr-logo" target="_parent"></a>
            <ul class="jp-controls">
              <li class="play-control"><a href="#" class="jp-play" tabindex="1">play</a></li>
              <li class="play-control"><a href="#" class="jp-pause" tabindex="1">pause</a></li>
              <li class="vol-control"><a href="#" class="jp-mute" tabindex="1">mute</a></li>
              <li class="vol-control"><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
            </ul>
          </div>
				<div id="jp_playlist_1" class="jp-playlist"></div>
			</div>
		</div>
  ';

  return '
          <input type="checkbox" id="live-options-toggle" />

            <div class="live-options">
              <ul>
                <li><a href="http://tunein.com/radio/Berlin-Community-Radio-s209811/">TuneIn stream</a></li>
                <li><a href="'. $base_url .'/sites/all/themes/bcr_bootstrap/streams/bcr.m3u">M3U file</a></li>
                <li><a href="http://berlincommunityradio.out.airtime.pro:8000/berlincommunityradio_b">Stream</a></li>
                <!-- <li><a href="'. $base_url .'/sites/all/themes/bcr_bootstrap/streams/bcr.pls">PLS file</a></li> -->
                <li>
                  <label for="live-options-toggle">
                    X Close
                  </label>
                </li>
              </ul>
              
            </div>

          <div class="container">
          ' . $player . $block . '
            <label class="mobile-links" for="live-options-toggle">
              Listen Live
            </label>


          </div>
  ';
}

/**
 * BCR LOGO block
 */
function bcr_logo_block_render() {
  return '<div id="logo-element"><a class="logo"></a></div>';
}


///**
// * BCR CHAT block
// */
//function bcr_chat_block_render() {
//}


/*
 * PAGE RENDER CALLBACKS
 */

/**
 * HELPER FUNCTION / PAGE RENDER CALLBACK
 * Front page render
 */
function bcr_front_page_getter() {
  return bcr_channels_grid_block_render();
}



